name: freibr
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^9.0.0
  device_info_plus: ^1.0.0
  flutter_facebook_login: ^3.0.0
  shared_preferences: ^2.0.3
  flutter_icons: ^1.1.0
  get: ^3.26.0
  provider: ^5.0.0
  image_picker:
  dio: ^4.0.0-beta4
  connectivity: ^3.0.2
  file_picker: ^3.0.0
  international_phone_input: ^1.0.4
  cupertino_icons: ^1.0.0
  flutter_rating_bar: ^4.0.0
  form_field_validator: ^1.0.1
  media_picker_builder: ^1.3.2
  flutter_native_splash: ^1.0.3
  permission_handler: ^6.0.1
  intl: ^0.17.0
  flutter_inappwebview: ^5.3.2
  uuid: ^3.0.4
  date_time_picker: ^2.0.0
  sizer: ^2.0.13
  flutter_easyloading: ^3.0.0
  # flutter_easyrefresh: ^2.2.1
  pull_to_refresh: ^2.0.0
  progressive_image: ^2.0.0
  # socket_io_client: ^1.0.1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  # property_change_notifier: ^0.2.0
  # speech_bubble: ^0.0.9
  # flutter_tagging: ^3.0.0
  # flutter_chips_input: ^1.10.0
  collection: ^1.15.0

  razorpay_flutter: 1.1.1
  flutter_downloader: ^1.3.3
  path_provider: ^2.0.2
  share: ^2.0.4
  uni_links: ^0.5.1
  url_launcher:
  flutter_slidable:

flutter_native_splash:
  color: "#2e2e2e"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  # color: "#ffffff"
  # image: assets/splash_full.png
  # color_dark: "#1a1a1a"
  # image_dark: assets/splash_full.png
  # android: true
  # ios: true
  # android_gravity: fill
  # ios_content_mode: scaleAspectFill

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/freibr.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/box/

  fonts:
    - family: Andina
      fonts:
        - asset: assets/fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: assets/fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/googlesansebold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 300
